# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    whale_window = 34
    thesis_group = "04"

    def __algorithm__(self):
        close = self.data.pv_close
        high = self.data.pv_high
        low = self.data.pv_low
        volume = self.data.pv_volume
        matched_val = self.data.fut_matched_value_vn30f1m_1d
        matched_vol = self.data.fut_matched_volume_vn30f1m_1d

        avg_trade = matched_val / matched_vol
        avg_trade_sma = self.feat.sma(avg_trade, timeperiod=self.whale_window)
        avg_trade_std = self.feat.rolling_std(avg_trade, window=self.whale_window)
        adx_val = self.feat.adx(high, low, close, timeperiod=7)

        whale = avg_trade > avg_trade_sma + 1.5 * avg_trade_std
        vol_sma = self.feat.sma(matched_vol, timeperiod=self.whale_window)
        price_compression = (self.feat.rolling_max(close, 10) - self.feat.rolling_min(close, 10)) / self.feat.rolling_min(close, 10) < 0.01

        long_setup = whale & price_compression & (matched_vol > vol_sma * 1.5) & (adx_val > 22)
        short_setup = whale & price_compression & (matched_vol > vol_sma * 1.5) & (adx_val > 22)
        exit_setup = self.op.crossed_below(close, self.feat.sma(close, 20)) | self.op.crossed_above(close, self.feat.sma(close, 20)) | (adx_val < 15)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

