# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    basis_window = 20
    thesis_group = "05"

    def __algorithm__(self):
        close = self.data.pv_close
        vn30_close = self.data.pv_vn30_close
        high = self.data.pv_high
        low = self.data.pv_low

        basis = close - vn30_close
        basis_z = self.feat.rolling_zscore(basis, window=self.basis_window)
        adx_val = self.feat.adx(high, low, close, timeperiod=21)
        matched_vol = self.data.fut_matched_volume_vn30f1m_1d
        vol_sma = self.feat.sma(matched_vol, timeperiod=self.basis_window)

        long_setup = (basis_z < -2.5) & (matched_vol < vol_sma) & (adx_val > 16)
        short_setup = (basis_z > 2.5) & (matched_vol < vol_sma) & (adx_val > 16)
        exit_setup = self.op.between(basis_z, -1, 1) | (adx_val < 10)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

