# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    z_window = 20
    z_threshold = 3.0
    thesis_group = "06"

    def __algorithm__(self):
        close = self.data.pv_close
        volume = self.data.pv_volume
        high = self.data.pv_high
        low = self.data.pv_low
        vn30_close = self.data.pv_vn30_close

        price_z = self.feat.price_z(close, timeperiod=self.z_window)
        vol_z = self.feat.volume_z(volume, timeperiod=self.z_window)
        atr_val = self.feat.atr(high, low, close, timeperiod=14)
        vola_z = self.feat.rolling_zscore(atr_val, window=self.z_window)
        ratio = close / vn30_close
        ratio_z = self.feat.rolling_zscore(ratio, window=self.z_window)

        composite = price_z + vol_z + vola_z + ratio_z

        adx_val = self.feat.adx(high, low, close, timeperiod=21)
        rsi = self.feat.rsi(close, timeperiod=21)
        return_roll = self.feat.returns(close, periods=14)

        core_long = (composite > self.z_threshold) & (rsi > 30) & (rsi < 70)
        core_short = (composite < -self.z_threshold) & (rsi > 30) & (rsi < 70)

        strong_long = core_long & (adx_val > 16) & (vol_z > 0) & (return_roll > 0)
        weak_long = core_long & (adx_val > 14) & (return_roll > 0)
        strong_short = core_short & (adx_val > 16) & (vol_z < 0) & (return_roll < 0)
        weak_short = core_short & (adx_val > 14) & (return_roll < 0)

        exit_setup = (self.op.abs(composite) < 1.0) | (adx_val < 10)

        self.set_positions(exit_setup, position=0)
        self.set_positions(weak_long, position=0.5)
        self.set_positions(strong_long, position=1)
        self.set_positions(weak_short, position=-0.5)
        self.set_positions(strong_short, position=-1)

