# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    kama_window = 10
    thesis_group = "01"

    def __algorithm__(self):
        close = self.data.pv_close

        mama, fama = self.feat.mama(close)
        kama = self.feat.kama(close, timeperiod=self.kama_window)

        long_setup = (close > kama) & (mama > fama)
        short_setup = (close < kama) & (mama < fama)
        exit_setup = self.op.crossed_below(close, kama) | self.op.crossed_above(close, kama)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

