# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    mean_window = 20
    thesis_group = "01"

    def __algorithm__(self):
        close = self.data.pv_close
        high = self.data.pv_high
        low = self.data.pv_low
        volume = self.data.pv_volume
        open_price = self.data.pv_open

        vwap_px = self.feat.vwap(high, low, close, volume)

        mean = self.feat.rolling_mean(vwap_px, window=self.mean_window)

        long_setup = vwap_px > mean
        short_setup = vwap_px < mean
        exit_setup = self.op.crossed_below(vwap_px, mean) | self.op.crossed_above(vwap_px, mean)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

