# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    mean_window = 8
    thesis_group = "01"

    def __algorithm__(self):
        close = self.data.pv_close
        high = self.data.pv_high
        low = self.data.pv_low
        volume = self.data.pv_volume
        open_price = self.data.pv_open

        volume_raw = self.data.pv_volume

        mean = self.feat.rolling_mean(volume_raw, window=self.mean_window)

        long_setup = volume_raw > mean
        short_setup = volume_raw < mean
        exit_setup = self.op.crossed_below(volume_raw, mean) | self.op.crossed_above(volume_raw, mean)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

