# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    mean_window = 20
    thesis_group = "01"

    def __algorithm__(self):
        close = self.data.pv_close
        high = self.data.pv_high
        low = self.data.pv_low
        volume = self.data.pv_volume
        open_price = self.data.pv_open

        weighted = self.feat.wclprice(high, low, close)

        mean = self.feat.rolling_mean(weighted, window=self.mean_window)

        long_setup = weighted > mean
        short_setup = weighted < mean
        exit_setup = self.op.crossed_below(weighted, mean) | self.op.crossed_above(weighted, mean)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

