# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    mean_window = 10
    thesis_group = "01"

    def __algorithm__(self):
        close = self.data.pv_close
        high = self.data.pv_high
        low = self.data.pv_low
        volume = self.data.pv_volume
        open_price = self.data.pv_open

        ohlc4 = self.feat.ohlc4(open_price, high, low, close)

        mean = self.feat.rolling_mean(ohlc4, window=self.mean_window)

        long_setup = ohlc4 > mean
        short_setup = ohlc4 < mean
        exit_setup = self.op.crossed_below(ohlc4, mean) | self.op.crossed_above(ohlc4, mean)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

