# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    q_window = 20
    thesis_group = "01"

    def __algorithm__(self):
        close = self.data.pv_close

        upper = self.feat.rolling_quantile(close, window=self.q_window, q=0.9)
        lower = self.feat.rolling_quantile(close, window=self.q_window, q=0.1)

        long_setup = close > upper
        short_setup = close < lower
        exit_setup = self.op.crossed_below(close, upper) | self.op.crossed_above(close, lower)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

