# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    z_window = 34
    thesis_group = "01"

    def __algorithm__(self):
        close = self.data.pv_close

        price_z = self.feat.rolling_zscore(close, window=self.z_window)

        long_setup = price_z < -1.5
        short_setup = price_z > 1.5
        exit_setup = self.op.between(price_z, -1, 1)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

