# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    mean_window = 34
    q_window = 20
    thesis_group = "01"

    def __algorithm__(self):
        close = self.data.pv_close

        mean = self.feat.rolling_mean(close, window=self.mean_window)
        upper = self.feat.rolling_quantile(close, window=self.q_window, q=0.8)
        lower = self.feat.rolling_quantile(close, window=self.q_window, q=0.2)

        long_setup = (close > upper) & (close > mean)
        short_setup = (close < lower) & (close < mean)
        exit_setup = self.op.crossed_below(close, mean) | self.op.crossed_above(close, mean)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

