# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    rsi_window = 14
    thesis_group = "03"

    def __algorithm__(self):
        close = self.data.pv_close
        high = self.data.pv_high
        low = self.data.pv_low

        sine, leadsine = self.feat.sine(close)
        rsi = self.feat.rsi(close, timeperiod=self.rsi_window)
        trend = self.feat.ht_trendline(close)
        adx_val = self.feat.adx(high, low, close, timeperiod=21)

        cycle_up = self.op.crossed_above(sine, leadsine)
        cycle_down = self.op.crossed_below(sine, leadsine)

        long_setup = cycle_up & (rsi > 30) & (adx_val > 16)
        short_setup = cycle_down & (rsi < 70) & (adx_val > 16)
        exit_setup = self.op.crossed_below(close, trend) | self.op.crossed_above(close, trend) | (adx_val < 10)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

