# XNOQuant - Alpha Bot Generated Strategy
# Auto-generated by tools/generate_strategies.py
# Do not edit manually
class CustomStrategy(SimpleAlgorithm):
    thesis_group = "03"

    def __algorithm__(self):
        close = self.data.pv_close
        high = self.data.pv_high
        low = self.data.pv_low

        trend = self.feat.ht_trendline(close)
        sine, leadsine = self.feat.sine(close)
        cycle_mode = self.feat.trendmode(close) == 0
        trend_mode = self.feat.trendmode(close) == 1
        adx_val = self.feat.adx(high, low, close, timeperiod=21)

        cycle_long = (sine > leadsine) & cycle_mode & (close > trend)
        cycle_short = (sine < leadsine) & cycle_mode & (close < trend)

        trend_long = (close > trend) & trend_mode & (adx_val > 16)
        trend_short = (close < trend) & trend_mode & (adx_val > 16)

        long_setup = cycle_long | trend_long
        short_setup = cycle_short | trend_short
        exit_setup = self.op.crossed_below(close, trend) | self.op.crossed_above(close, trend) | (adx_val < 10)

        self.set_positions(exit_setup, position=0)
        self.set_positions(long_setup, position=1)
        self.set_positions(short_setup, position=-1)

